# Generated by Django 5.1.3 on 2024-11-21 00:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='staffs_profile',
            name='experience',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs_profile',
            name='qualifications',
            field=models.ManyToManyField(to='Staffs.qualification'),
        ),
        migrations.AddField(
            model_name='staffs_profile',
            name='Marital_status',
            field=models.ManyToManyField(to='Staffs.relationship'),
        ),
    ]
